application: museums-map
version: 1
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js